groupName: cert-manager-webhook-inwx.smueller18.gitlab.com

credentialsSecretRefs:
- inwx-credentials

deployment:
  loglevel: 2

certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

image:
  repository: ghcr.io/sockmister/cert-manager-webhook-inwx
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 443

resources: {}
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 10m
#    memory: 24Mi

nodeSelector: {}

tolerations: []

affinity: {}
